baseURL = "https://president810.github.io/GEB2503_Project/"
languageCode = "en-us"
title = "GEB2503 Smart City Blog"
contentdir = "content"
layoutdir = "layouts"
publishDir = "docs"
canonifyurls = true
theme = "hugo-swift-theme"